export type GlobalAttribute = 'accesskey' | 'autocapitalize' | 'autofocus' | 'class' | 'contenteditable' | 'dir' | 'draggable' | 'enterkeyhint' | 'hidden' | 'id' | 'inert' | 'inputmode' | 'is' | 'itemid' | 'itemprop' | 'itemref' | 'itemscope' | 'itemtype' | 'lang' | 'nonce' | 'popover' | 'slot' | 'spellcheck' | 'style' | 'tabindex' | 'title' | 'translate';
interface AttributeMap extends Record<keyof HTMLElementTagNameMap, string> {
	'a': GlobalAttribute | 'charset' | 'coords' | 'download' | 'href' | 'hreflang' | 'name' | 'ping' | 'referrerpolicy' | 'rel' | 'rev' | 'shape' | 'target' | 'type';
	'applet': GlobalAttribute | 'align' | 'alt' | 'archive' | 'code' | 'codebase' | 'height' | 'hspace' | 'name' | 'object' | 'vspace' | 'width';
	'area': GlobalAttribute | 'alt' | 'coords' | 'download' | 'href' | 'hreflang' | 'nohref' | 'ping' | 'referrerpolicy' | 'rel' | 'shape' | 'target' | 'type';
	'audio': GlobalAttribute | 'autoplay' | 'controls' | 'crossorigin' | 'loop' | 'muted' | 'preload' | 'src';
	'base': GlobalAttribute | 'href' | 'target';
	'basefont': GlobalAttribute | 'color' | 'face' | 'size';
	'blockquote': GlobalAttribute | 'cite';
	'body': GlobalAttribute | 'alink' | 'background' | 'bgcolor' | 'link' | 'text' | 'vlink';
	'br': GlobalAttribute | 'clear';
	'button': GlobalAttribute | 'disabled' | 'form' | 'formaction' | 'formenctype' | 'formmethod' | 'formnovalidate' | 'formtarget' | 'name' | 'popovertarget' | 'popovertargetaction' | 'type' | 'value';
	'canvas': GlobalAttribute | 'height' | 'width';
	'caption': GlobalAttribute | 'align';
	'col': GlobalAttribute | 'align' | 'char' | 'charoff' | 'span' | 'valign' | 'width';
	'colgroup': GlobalAttribute | 'align' | 'char' | 'charoff' | 'span' | 'valign' | 'width';
	'data': GlobalAttribute | 'value';
	'del': GlobalAttribute | 'cite' | 'datetime';
	'details': GlobalAttribute | 'open';
	'dialog': GlobalAttribute | 'open';
	'dir': GlobalAttribute | 'compact';
	'div': GlobalAttribute | 'align';
	'dl': GlobalAttribute | 'compact';
	'embed': GlobalAttribute | 'height' | 'src' | 'type' | 'width';
	'fieldset': GlobalAttribute | 'disabled' | 'form' | 'name';
	'font': GlobalAttribute | 'color' | 'face' | 'size';
	'form': GlobalAttribute | 'accept' | 'accept-charset' | 'action' | 'autocomplete' | 'enctype' | 'method' | 'name' | 'novalidate' | 'target';
	'frame': GlobalAttribute | 'frameborder' | 'longdesc' | 'marginheight' | 'marginwidth' | 'name' | 'noresize' | 'scrolling' | 'src';
	'frameset': GlobalAttribute | 'cols' | 'rows';
	'h1': GlobalAttribute | 'align';
	'h2': GlobalAttribute | 'align';
	'h3': GlobalAttribute | 'align';
	'h4': GlobalAttribute | 'align';
	'h5': GlobalAttribute | 'align';
	'h6': GlobalAttribute | 'align';
	'head': GlobalAttribute | 'profile';
	'hr': GlobalAttribute | 'align' | 'noshade' | 'size' | 'width';
	'html': GlobalAttribute | 'manifest' | 'version';
	'iframe': GlobalAttribute | 'align' | 'allow' | 'allowfullscreen' | 'allowpaymentrequest' | 'allowusermedia' | 'frameborder' | 'height' | 'loading' | 'longdesc' | 'marginheight' | 'marginwidth' | 'name' | 'referrerpolicy' | 'sandbox' | 'scrolling' | 'src' | 'srcdoc' | 'width';
	'img': GlobalAttribute | 'align' | 'alt' | 'border' | 'crossorigin' | 'decoding' | 'fetchpriority' | 'height' | 'hspace' | 'ismap' | 'loading' | 'longdesc' | 'name' | 'referrerpolicy' | 'sizes' | 'src' | 'srcset' | 'usemap' | 'vspace' | 'width';
	'input': GlobalAttribute | 'accept' | 'align' | 'alt' | 'autocomplete' | 'checked' | 'dirname' | 'disabled' | 'form' | 'formaction' | 'formenctype' | 'formmethod' | 'formnovalidate' | 'formtarget' | 'height' | 'ismap' | 'list' | 'max' | 'maxlength' | 'min' | 'minlength' | 'multiple' | 'name' | 'pattern' | 'placeholder' | 'popovertarget' | 'popovertargetaction' | 'readonly' | 'required' | 'size' | 'src' | 'step' | 'type' | 'usemap' | 'value' | 'width';
	'ins': GlobalAttribute | 'cite' | 'datetime';
	'isindex': GlobalAttribute | 'prompt';
	'label': GlobalAttribute | 'for' | 'form';
	'legend': GlobalAttribute | 'align';
	'li': GlobalAttribute | 'type' | 'value';
	'link': GlobalAttribute | 'as' | 'blocking' | 'charset' | 'color' | 'crossorigin' | 'disabled' | 'fetchpriority' | 'href' | 'hreflang' | 'imagesizes' | 'imagesrcset' | 'integrity' | 'media' | 'referrerpolicy' | 'rel' | 'rev' | 'sizes' | 'target' | 'type';
	'map': GlobalAttribute | 'name';
	'menu': GlobalAttribute | 'compact';
	'meta': GlobalAttribute | 'charset' | 'content' | 'http-equiv' | 'media' | 'name' | 'scheme';
	'meter': GlobalAttribute | 'high' | 'low' | 'max' | 'min' | 'optimum' | 'value';
	'object': GlobalAttribute | 'align' | 'archive' | 'border' | 'classid' | 'codebase' | 'codetype' | 'data' | 'declare' | 'form' | 'height' | 'hspace' | 'name' | 'standby' | 'type' | 'typemustmatch' | 'usemap' | 'vspace' | 'width';
	'ol': GlobalAttribute | 'compact' | 'reversed' | 'start' | 'type';
	'optgroup': GlobalAttribute | 'disabled' | 'label';
	'option': GlobalAttribute | 'disabled' | 'label' | 'selected' | 'value';
	'output': GlobalAttribute | 'for' | 'form' | 'name';
	'p': GlobalAttribute | 'align';
	'param': GlobalAttribute | 'name' | 'type' | 'value' | 'valuetype';
	'pre': GlobalAttribute | 'width';
	'progress': GlobalAttribute | 'max' | 'value';
	'q': GlobalAttribute | 'cite';
	'script': GlobalAttribute | 'async' | 'blocking' | 'charset' | 'crossorigin' | 'defer' | 'fetchpriority' | 'integrity' | 'language' | 'nomodule' | 'referrerpolicy' | 'src' | 'type';
	'select': GlobalAttribute | 'autocomplete' | 'disabled' | 'form' | 'multiple' | 'name' | 'required' | 'size';
	'slot': GlobalAttribute | 'name';
	'source': GlobalAttribute | 'height' | 'media' | 'sizes' | 'src' | 'srcset' | 'type' | 'width';
	'style': GlobalAttribute | 'blocking' | 'media' | 'type';
	'table': GlobalAttribute | 'align' | 'bgcolor' | 'border' | 'cellpadding' | 'cellspacing' | 'frame' | 'rules' | 'summary' | 'width';
	'tbody': GlobalAttribute | 'align' | 'char' | 'charoff' | 'valign';
	'td': GlobalAttribute | 'abbr' | 'align' | 'axis' | 'bgcolor' | 'char' | 'charoff' | 'colspan' | 'headers' | 'height' | 'nowrap' | 'rowspan' | 'scope' | 'valign' | 'width';
	'textarea': GlobalAttribute | 'autocomplete' | 'cols' | 'dirname' | 'disabled' | 'form' | 'maxlength' | 'minlength' | 'name' | 'placeholder' | 'readonly' | 'required' | 'rows' | 'wrap';
	'tfoot': GlobalAttribute | 'align' | 'char' | 'charoff' | 'valign';
	'th': GlobalAttribute | 'abbr' | 'align' | 'axis' | 'bgcolor' | 'char' | 'charoff' | 'colspan' | 'headers' | 'height' | 'nowrap' | 'rowspan' | 'scope' | 'valign' | 'width';
	'thead': GlobalAttribute | 'align' | 'char' | 'charoff' | 'valign';
	'time': GlobalAttribute | 'datetime';
	'tr': GlobalAttribute | 'align' | 'bgcolor' | 'char' | 'charoff' | 'valign';
	'track': GlobalAttribute | 'default' | 'kind' | 'label' | 'src' | 'srclang';
	'ul': GlobalAttribute | 'compact' | 'type';
	'video': GlobalAttribute | 'autoplay' | 'controls' | 'crossorigin' | 'height' | 'loop' | 'muted' | 'playsinline' | 'poster' | 'preload' | 'src' | 'width';
}
export type HTMLTag = keyof AttributeMap & keyof HTMLElementTagNameMap;
export type HTMLAttribute<T extends HTMLTag> = AttributeMap[T];
